version: '2'
services:
  thefakebook_web:
    build: .
    command: >
      bash -c "python manage.py makemigrations core
      && python manage.py migrate
      && python manage.py test
      && gunicorn thefakebook.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - thefakebook_db
    volumes:
      - .:/src
    ports:
      - "8000:8000"

  thefakebook_db:
    image: postgres:latest